### ISSUE TITLE
Hoe krijg je dit correct geïnstalleerd?

### ISSUE THREAD

**Issue by nozamo** [basst85/bunq_pay#11]
Sorry miss ben k wel een beetje noob maar ik krijg dit maar niet werkend zou iemand mij dit kunnen uitleggen? (de stap tot en met de composer is gelukt maar veder krijg ik hem niet)

**Comment by D-on-GitHub** [comment]
Na composer install:

- Open install.php en vul het juiste pad naar de database in.
- Ful je API-key in in install.php
- Voer install.php uit
- Daarna kan je, door index.php te benaderen, gebruik maken van bunq_pay.

**Comment by nozamo** [comment]
ik blijf dit maar krijgen

Fatal error: Uncaught bunq\Exception\BunqException: Generating a new private key failed. See "http://php.net/manual/en/function.openssl-pkey-new.php" for more info. in C:\xampp\htdocs\bunq_pay-master\vendor\bunq\sdk_php\src\Security\KeyPair.php:66 Stack trace: #0 C:\xampp\htdocs\bunq_pay-master\vendor\bunq\sdk_php\src\Context\ApiContext.php(143): bunq\Security\KeyPair::generate() #1 C:\xampp\htdocs\bunq_pay-master\vendor\bunq\sdk_php\src\Context\ApiContext.php(134): bunq\Context\ApiContext->initializeInstallationContext() #2 C:\xampp\htdocs\bunq_pay-master\vendor\bunq\sdk_php\src\Context\ApiContext.php(115): bunq\Context\ApiContext->initialize('bunq_pay v1', Array) #3 C:\xampp\htdocs\bunq_pay-master\install.php(44): bunq\Context\ApiContext::create(Object(bunq\Util\BunqEnumApiEnvironmentType), 'bur My api is here', 'bunq_pay v1', Array) #4 {main} thrown in C:\xampp\htdocs\bunq_pay-master\vendor\bunq\sdk_php\src\Security\KeyPair.php on line 66

en ik heb in xampp openssl al aan gezet
zou iemand kunnen helpen?

**Comment by D-on-GitHub** [comment]
Ik zou zeggen probeer het even op een Linux machientje, daar kan het eenvoudiger zijn.

**Comment by basst85** [comment]
Het lijkt op een fout in de configuratie van xampp, mogelijk kan de OpenSSL config (openssl.cnf) niet geladen worden?
