### ISSUE TITLE
bunqMonetaryAccount

### ISSUE THREAD

**Issue by hooli01** [basst85/bunq_pay#3]
Hi, 
I am trying to get your code working, but i dont understand where do you get this data from?
$bunqUserId = '';
$bunqMonetaryAccount = '';
$bunqAuthToken = ''; //To do: Automatic get token

**Comment by basst85** [comment]
Hello!
I'm working on a new version, that uses the official bunq PHP SDK. And with some extra documentation :-)

**Comment by hooli01** [comment]
the problem with that code (the official BUNQ sdk) is that it requires php7. Our server is still running 5.5.9... :-( so i was hoping to get your code up and running....

**Comment by basst85** [comment]
Fixed by 55a1a5e9b485ccee42f3a924127bab7ba02b49c9
