### ISSUE TITLE
Database is after the installation readonly

### ISSUE THREAD

**Issue by jesgeerts** [basst85/bunq_pay#8]
`2018/04/09 12:10:18 [error] 3187#3187: *2148 FastCGI sent in stderr: "PHP message: PHP Warning:  SQLite3::exec(): attempt to write a readonly database in /var/www/ph-parking/bunq_pay/classes/database.php on line 25" while reading response header from upstream, client: 40.68.46.18, server: , request: "GET /bunq_pay/install.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", 
2018/04/09 12:12:02 [error] 3187#3187: *2150 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: bunqContext in /var/www/ph-parking/bunq_pay/classes/database.php on line 19
PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: json_decode error: Syntax error in /var/www/ph-parking/bunq_pay/vendor/guzzlehttp/guzzle/src/functions.php:304
Stack trace:
#0 /var/www/ph-parking/bunq_pay/vendor/bunq/sdk_php/src/Context/ApiContext.php(214): GuzzleHttp\json_decode('', true)
#1 /var/www/ph-parking/bunq_pay/bunqPayRequest.php(55): bunq\Context\ApiContext::fromJson('')
#2 {main}
  thrown in /var/www/ph-parking/bunq_pay/vendor/guzzlehttp/guzzle/src/functions.php on line 304" while reading response header from upstream, client: 40.68.46.18, server: , request: "GET /bunq_pay/bunqPayRequest.php?amount=5&description=pay%20me HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "`

**Comment by basst85** [comment]
@jesgeerts Thanks for reporting.
The database directory and the db-file are writable by the web user before running install.php ?
